### ISSUE TITLE
Search comes up with no results?

### ISSUE THREAD

**Issue by Ventus250** [Rascalov/Anki-Simple-Forvo-Audio#11]
I'm on the latest anki version and this used to work fine, but when I search for something now it just says no results found. I tried with words that worked before but it has no results for them either.
I'm on a mac btw.

**Comment by Rascalov** [comment]
Seems like all operating systems are affected
They probably changed something on the site, which breaks the scraper.
I will check the changes today and push a solution, will update here.

**Comment by Rascalov** [comment]
https://github.com/Rascalov/Anki-Simple-Forvo-Audio/commit/2dbe4579db518fa894f196877d0a2fe8956630ef and https://github.com/Rascalov/Anki-Simple-Forvo-Audio/commit/732c580f6c98f43bc5fae7b8b952a41d538f5c7f Fixed the scraper issue. 
Please update your addon via Anki's addon section or download the new release (will need to edit your config again).

Closing this now. If Issues still arise you can make a new issue.
