### ISSUE TITLE
Preview audio and choose audio causes error

### ISSUE THREAD

**Issue by Ventus250** [Rascalov/Anki-Simple-Forvo-Audio#14]
I'm on the latest anki version and when I click the preview audio and choose audio, it comes up with an error.
I'm on a mac btw trying to use Japanese audio.

<img width="461" alt="Screenshot 2022-08-04 at 00 26 32" src="https://user-images.githubusercontent.com/109320003/182729520-d7a8488c-a7bb-46a1-8371-c406d867c2c8.png">

<img width="479" alt="Screenshot 2022-08-04 at 00 26 56" src="https://user-images.githubusercontent.com/109320003/182729563-ae0ac524-9074-455b-9acc-0702d528c49e.png">

Idk if these screenshots help? First one is for "preview audio", second is for "choose and close"

**Comment by Rascalov** [comment]
Yeah looks like you need to add the downloadpath in the config.
See if this helps https://github.com/Rascalov/Anki-Simple-Forvo-Audio#installation
