### ISSUE TITLE
this addon is what i need but i cant embed the audio at the last step

### ISSUE THREAD

**Issue by cindynap** [Rascalov/Anki-Simple-Forvo-Audio#15]
错误
发生了一个错误。请在启动Anki时按住「Shift」键临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki， 请重复上述步骤直至找到引起错误的插件。 找到引起错误的插件后，请反馈给插件作者。 调试信息：
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-27 22:59:21

Caught exception:
Traceback (most recent call last):
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 151, in <lambda>
    previewButton.clicked.connect(lambda: self.previewAudio(ankiAudioObject))
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 164, in previewAudio
    fullpath = self.getDefinteConfigPath() + AnkiAudioGlobals.TEMP_FILE_PREFIX + audioObject.getBucketFilename()
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 203, in getDefinteConfigPath
    if(configPath[-1] != "\\" or configPath[-1] !="/"):
IndexError: string index out of range

**Comment by MrVhek** [comment]
Did you setup the download path as specified in the setup ? 
I think the error shall be more explicit like raise Exception("Missing download path configuration").

**Comment by Rascalov** [comment]
@cindynap Have you tried @MrVhek's solution?
This part of the readme gives more info where to edit the downloadPath
https://github.com/Rascalov/Anki-Simple-Forvo-Audio#installation

**Comment by cindynap** [comment]
Hi Thanks for response.

Unfortunately the path setup fails. I attach the error page which is just
telling invalid config.

This is the code I use
C:\\Users\\cindy\\AppData\\Roaming\\Anki2\\Cindy French\\collection.media

I am using windows 10.


Regards
Cindy


MrVhek ***@***.***> 于2022年8月28日周日 11:35写道：

**Comment by cindynap** [comment]
😚 Now it works.

Regards
Cindy


Tim ***@***.***> 于2022年8月30日周二 04:11写道：
