### ISSUE TITLE
I cannot add audios to a deck at the same time. How can i solve it? if you can help me i would be grateful.

### ISSUE THREAD

**Issue by ZhangYan2580** [Rascalov/Anki-Simple-Forvo-Audio#16]

**Comment by proancestor** [comment]
the plugin you write really helped a lot.but this problem happens to me too.
neither on the Version ⁨2.1.54 nor 2.1.55, the “Add Forvo TTS to deck” menu didn't appear, so i cannot download the audio in bulk. would you kindly fix this? really appreciate.
![无标题](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/assets/134911006/dea523ef-2e54-41fa-b75f-0e879f4f29c5)

**Comment by Rascalov** [comment]
Thank you for your interest and apologies for the late reply.
I have re-added this Auto TTS menu to the Tools menubar with the latest update, which also no longer requires a downloadPath to be set. 

Please update your extension and confirm it works on your end, I can close this issue then.

**Comment by Rascalov** [comment]
Thank you for the feedback. Glad to hear that it still works.
I will close this issue for now.
