### ISSUE TITLE
No "Add forvo audio" option

### ISSUE THREAD

**Issue by rc-ops** [Rascalov/Anki-Simple-Forvo-Audio#2]
Hi. I'm trying to use the addon, but there's no option to add audio when I right click. Tried via the Add new card dialog and through the Edit an existing one. I've installed through ankiweb and directly from the repository, same result.
![2021-04-23 21_47_12-Greenshot](https://user-images.githubusercontent.com/72221896/115941908-e1238200-a47d-11eb-8d60-09f03e8e60de.png)

I'm using Anki 2.1.43 on Windows 10.

**Comment by Rascalov** [comment]
That's odd, I'll have to get on windows and see if I can reproduce this.

**Comment by Rascalov** [comment]
I installed Anki 2.1.43 on Windows 10 and it works on my end (though the autofil on selected text does not, so that needs a fix). Even with AwesomeTTS installed it still shows the option.

**Comment by patoniilista** [comment]
Only the option "add forvo to deck" works for me

![2021-04-23 22_56_16-User 1 - Anki](https://user-images.githubusercontent.com/72221896/115943585-2304f600-a487-11eb-8a6d-ca40637c04c8.png)
