### ISSUE TITLE
Search doesn't find anything?

### ISSUE THREAD

**Issue by elDub1234** [Rascalov/Anki-Simple-Forvo-Audio#22]
I have Anki 2.1.65 and have just installed this addon, but I get no results for even the simplest words, e.g. hola in Spanish. I see this was fixed before. Is there a new bug?

**Comment by Rascalov** [comment]
I think your guess is correct, languages that have a lot of distinct accents have a differently structured page. I recall doing a quick fix for English for that reason. 
If it is a similar issue, then I should be able to fix this tonight and push out an update.

**Comment by Rascalov** [comment]
Alright, one small change did the trick.
Should be good now (for Spanish at least).
You can update the extension and let me know if it works for you!

**Comment by elDub1234** [comment]
Thank you. Yes that works wonderfully. I am very grateful.

I did notice a small thing where if I try to put the same sound onto more than one card it errors out because it says the sound file already exists. It would be nice if it could just pick up the existing name and add it to the field?

Thanks again

**Comment by Rascalov** [comment]
Sounds annoying, haven't encountered that myself. 
If you want, you can post a new issue detailing that problem with steps to reproduce and what errors it specifically shows. I will pick it up from there. 
Your latter suggestion might take some more time, and may be worth its own issue (as a feature request)
Closing this issue for now as fixed.
