### ISSUE TITLE
Qt5 compatibility code will no longer be supported in the upcoming version of Anki

### ISSUE THREAD

**Issue by Expertium** [Rascalov/Anki-Simple-Forvo-Audio#24]
The current version of the add-on doesn't work in [the most recent beta](https://github.com/ankitects/anki/releases/tag/23.10rc2), I assume it's because Qt5 is no longer supported. I recommend updating this add-on to support Qt6.

**Comment by Rascalov** [comment]
Thank you for the heads up, I believe some of this coincides with https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/21 and I prepared the changes for it. 
On Tuesday I will look over the changes and publish them.

**Comment by Rascalov** [comment]
Changes are made are this [branch](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/tree/DeprecationPrevention) , I downloaded the build you linked and it works as intended. 
I will attempt to fix https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/17 today as well so a new release/update will be available the end of the day.
You can also install the branch version of the addon if you need to use it today in QT6. Later in the day you can download/upgrade from ankiweb as normal.

**Comment by Rascalov** [comment]
Main release has been updated for QT6!
Should be good for download/update from ankiweb!
If you still encounter problems, you can create another issue and I'll be sure to get to it!
