### ISSUE TITLE
Doesn't work in Anki 23.12 beta3

### ISSUE THREAD

**Issue by Expertium** [Rascalov/Anki-Simple-Forvo-Audio#28]
You can download the beta here: https://github.com/ankitects/anki/releases/tag/23.12beta3
I don't get any error messages, just "No results found..." for any word of any language.

**Comment by Rascalov** [comment]
I feared this day might come. 
No version issue I'm afraid.
Forvo now seems to have adopted a cloudflare browser check. This stops the scraper in its tracks, as it does not deal with javascript (even if it did, it could not solve any challenge cloudflare might give them)  
I'm looking for a quick fix, but this is a common way that gets scraping projects killed or extremely tedious to use.

**Comment by Expertium** [comment]
Ah, I see. I'm currently downloading the torrent from here: https://forum.freemdict.com/t/topic/11947
It seems like I will have to manually add the audio to the collection.media folder and manually type the name of the audio file in the field every time I want to add a file. Better than nothing, I guess, but impractical, and I don't have the coding skills to make a version of your add-on that can access local files.
Btw, would you consider hosting all of these files a viable solution? As in, when a user wants to download a file, it will be downloaded from your server rather than from Forvo itself.

**Comment by Rascalov** [comment]
Wrote a small thing about it https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/29
Closing this on in favor of that issue. 

> Btw, would you consider hosting all of these files a viable solution? As in, when a user wants to download a file, it will be downloaded from your server rather than from Forvo itself.
I had indeed done something like this for the Automated variant of this extension, it was sadly a major mess of databases and CDNs to keep it from being a monthly expense. I don't see myself giving it another go.

**Comment by Rascalov** [comment]
Sorry for the late update: But it seems the extension still works on residential IPs, So I edited my statement at  https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/29

**Comment by Expertium** [comment]
Nice! BTW, I found that lingualibre works well.
