### ISSUE TITLE
No Brazilian Portuguese results

### ISSUE THREAD

**Issue by efflang** [Rascalov/Anki-Simple-Forvo-Audio#30]
The add-on doesn't seem to recognize Portuguese audio with a Brazilian pronunciation. 

It only returns audio from Portugal, if it exists; otherwise it returns "no results found". 

The latter happens maybe 50% of the time, since Forvo has way more clips from Brazil.

**Comment by Rascalov** [comment]
Got time for this issue next week.
I assume it's similar to how the British and American English were categorized in Forvo, so I don't expect. 

In the mean time, could you give me some example words were this occurs? I'll test whether my fix works based on those words.

**Comment by Rascalov** [comment]
I tested a more general approach that captures all the accents on the words. Seems to work for both English and Portuguese in terms of accents.  
I'll release it on Friday. If you want to try before that, you can get it from this branch https://github.com/Rascalov/Anki-Simple-Forvo-Audio/tree/fix/accents

**Comment by Rascalov** [comment]
done, if you still find problems relating to accents, you can reopen the issue.
