### ISSUE TITLE
Wrong audio

### ISSUE THREAD

**Issue by Expertium** [Rascalov/Anki-Simple-Forvo-Audio#35]
I think instead of describing the steps to reproduce this problem, it's easier to demonstrate if I show you the video (please make sure that the audio isn't muted). TLDW: the audio doesn't correspond to the word. I don't know if this happens with other languages.

https://github.com/Rascalov/Anki-Simple-Forvo-Audio/assets/83031600/843ee4ff-a1e9-4609-b683-353ca41d4fca

P.S. I would really appreciate it if you implemented [this](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/27).

**Comment by Rascalov** [comment]
Interesting, I'll take a look. 
Your other request is in the works, just need to find a suitable way to make it happen, I'll update you on that issue separately

**Comment by Expertium** [comment]
I just checked Japanese, it's completely broken: "no results" for any word.

**Comment by Rascalov** [comment]
I fear that's Forvo's anti-scraping protection that comes online every so often. Can you confirm whether other languages do not work?

**Comment by Expertium** [comment]
Idk. Sorry, I only use the add-on for English and Japanese.

**Comment by Rascalov** [comment]
no problem, does it work still work for English?

**Comment by Expertium** [comment]
Well, yes, but also no. I just tried it on "overtake" again, like in the video, and got "No results". But it works for other words.

**Comment by Expertium** [comment]
Japanese stopped working completely :/

**Comment by Rascalov** [comment]
yup, I've seen it for a bit now.
On Sunday I will release a new version of the addon that will create a fallback to another source.
This source has audios for most of the languages, including Japanese (I'm adding English to the dataset today).

**Comment by Rascalov** [comment]
New release is published, I'll close this issue. If you experience any issues, you can create a new issue.
