### ISSUE TITLE
sounds are not downloading apparently due to space in language ID string

### ISSUE THREAD

**Issue by NartimHenriksen** [Rascalov/Anki-Simple-Forvo-Audio#44]
OS: Ubuntu 22.04.5 LTS

Anki:
Version ⁨24.06.3 (d678e393)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

Config file:
{
    "LastSelectedField": "Default Audio or Toned Ending",
    "LastSelectedLanguage": "Mandarin Chinese_zh",
    "MaxForvoDownloads": 100,
    "Remember language on a per deck basis": "True",
    "Use sources besides Forvo": "False",
    "audioFileExtension": "mp3",
    "downloadPath": "/home/my-user/.local/share/Anki2/User 1/collection.media/",
    "ignorePunctuation": "False"
}

When using the context menu feature, I can search and get results but there is no audio when pressing preview.  I have the latest version of MPV and lame, and audio plays fine in anki otherwise.
When I press download, it adds the audio insertion string (like [example.mp3]) in the field, but the audio file does not get added to collection.media and it doesn't work on the card. I checked again that the path is correct, and it seems to be. Also tried with empty path string in config and it was the same result.

When I launch anki from command line it prints out this when I search

FORVO: Looking for 卫生间
HTTP Error 403: Forbidden
FORVO: Word not found (Page does not exist!)
Forga: looking up: '卫生间' in language 'Mandarin Chinese_zh'
URL: http://forga.charitycook.com:8001/audios?language=Mandarin Chinese_zh&value=卫生间
response status: 200
Forga: Results count: 3
卫生间-73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3
adding result
卫生间-04b130387bb4250b6032ccbcad4fceefe03f4d4ef879b982288c69a161da9d80.mp3
adding result
卫生间-1158397687aa957eafa75b3c4351c0324a3894006d04555e49c37e06773f9019.mp3
adding result

When i press preview audio on the top file it says

/home/martin/.local/share/Anki2/User 1/collection.media//TEMP_AUDIO_FILE-卫生间-73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3 is not a file, downloading...
Downloading: link: https://core.fuga.cloud:8080/f418df3e42294cbab0e706d75488a4fb:forga/Mandarin Chinese_zh/7/3/a/73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3 path: /home/martin/.local/share/Anki2/User 1/collection.media// filename: TEMP_AUDIO_FILE-卫生间-73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3
Failed to download TEMP_AUDIO_FILE-卫生间-73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3
URL can't contain control characters. '/f418df3e42294cbab0e706d75488a4fb:forga/Mandarin Chinese_zh/7/3/a/73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3' (found at least ' ')

looks like it is bugged because there is a space in the language name 'Mandarin Chinese_zh'

when I click download it says

卫生间-73a9badd0a120e8cef3fc9c04edfde5a77732d42f7870862f55329913be5aad7.mp3
Chinese_zh'

again, its printing out the part of the language string that comes after the space. Seems like a bug with quotes or something

**Comment by Rascalov** [comment]
Good catch. Should be fixed now, no update needed, give it a try.

**Comment by NartimHenriksen** [comment]
Works, thank you very much!
