### ISSUE TITLE
No longer working for English language only

### ISSUE THREAD

**Issue by Schaffah** [Rascalov/Anki-Simple-Forvo-Audio#7]
Hello,

Any time I search for a word, it will not show any results if it's in english even after confirming it's on Fovo. However; the other languages still work.

I think maybe Fovo changed something for english? 

Anyways, if there's a solution or something i can edit in the ini files please let me know, I love your addon!

**Comment by Rascalov** [comment]
Sorry for late reply, I told myself I would get back to this when I received the mail, but here I am 3 days later...

It is probably exactly as you say, they changed some of the site's html for the English_us and English_gb sections and now the scraper can't find anything. 
I expect to put out a fix today, if not I will mention it here.

**Comment by Rascalov** [comment]
Commited changes to https://github.com/Rascalov/Anki-Simple-Forvo-Audio/commit/856e3f609747f63641c4d3fb89e3ab3bdfe82429
To update the Addon, either update the anki extension in Anki's add on menu or Redownload it from Anki's official site (or download the updated release from github).
In case the Audio does not work immediately, you have to set a downloadpath as mentioned here https://github.com/Rascalov/Anki-Simple-Forvo-Audio#installation

I tested the extension on the latest Anki (QT5) and it showed results for all English Accents. 
Let me know if it works for you, if it does I will close this issue.

**Comment by Schaffah** [comment]
Okay so! Your addon Update made the addon stop working on my older Anki 1.49 i think? So I updated to the new one QT5. It failed to install. 

I don't really like the newer Anki, so I downgraded it back to 1.49. Your addon was gone / no longer working on 1.49, but luckily I had the file saved on my end because I was moving all my addons to a 2nd computer lol. So I just popped the old one back in. 

Anki English still does not work. But. For now, Ill get the german pronunciation on these terms. They are medical terms so its just heavily accented but at least i can figure out how to say them lol. I take my boards next Thursday so ill just make do lol.

Thanks for your help Tim! Sorry us Windows users have so many errors!

**Comment by Schaffah** [comment]
Hi! Just wanted to let you know that I found a way to make your update work with the older version - 1.49; 

I downloaded the new one you made, and moved copy-pasted the scraper file into the old one. So it's working again. 

Thanks again for this addon! I wish I had the skills to write code and make things like this lol.

**Comment by Rascalov** [comment]
Glad you figured it out! I guess I messed up with compatability, your discovery helps me set it straight (Got some time again in the weekend).

> Thanks again for this addon! I wish I had the skills to write code and make things like this lol.
Glad to hear you enjoy it. Hehehe, an experienced programmer would probably cringe a bit at my work, should you one day decide to learn more about it, you would probably write a better version than mine :smile: 

Closing this Issue as Solved!

**Comment by Rascalov** [comment]
> Thanks for your help Tim! Sorry us Windows users have so many errors!

Hehe, that's enitrely my problem, friend. I should probably test on more systems than Linux before I release. Would Save you all a lot of headaches.

Closing for real now
