### ISSUE TITLE
can not be used on the latest anki

### ISSUE THREAD

**Issue by ZhangYan2580** [Rascalov/Anki-Simple-Forvo-Audio#8]

**Comment by ZhangYan2580** [comment]
> Version ⁨2.1.53 (QT5, Linux) works on my end. What Operating System are you Using? If you use the QT6 version, I have not yet tested support for that version.

QT5 window

**Comment by Rascalov** [comment]
I'll check the windows version this weekend

**Comment by Rascalov** [comment]
I tested it on a Windows vm for 2.1.53, Seemed to work just fine.
I could not test audio cause my vmware needed a different driver. But adding audio gave no issue and was downloaded correctly.
